# Generated by Django 5.0.6 on 2024-10-05 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Museo", "0002_museo_sala_imagen_alter_exposicion_autor_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exposicion",
            name="museo",
        ),
        migrations.AddField(
            model_name="exposicion",
            name="relative_position",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="exposicion",
            name="height",
            field=models.FloatField(default=0.2),
        ),
        migrations.AlterField(
            model_name="exposicion",
            name="posX",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="exposicion",
            name="posY",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="exposicion",
            name="sala",
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.CASCADE, to="Museo.sala"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="exposicion",
            name="width",
            field=models.FloatField(default=0.2),
        ),
    ]
