# Generated by Django 5.0.6 on 2024-10-09 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Museo", "0004_rename_relative_position_exposicion_absolute_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="exposicion",
            name="bg_color",
            field=models.CharField(default="#04ff00", max_length=7),
        ),
        migrations.AddField(
            model_name="exposicion",
            name="border",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="exposicion",
            name="border_color",
            field=models.CharField(default="#0000ff", max_length=7),
        ),
        migrations.AddField(
            model_name="museo",
            name="bg_color",
            field=models.CharField(default="#04ff00", max_length=7),
        ),
        migrations.AddField(
            model_name="museo",
            name="border",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="museo",
            name="border_color",
            field=models.CharField(default="#0000ff", max_length=7),
        ),
        migrations.AddField(
            model_name="sala",
            name="bg_color",
            field=models.CharField(default="#04ff00", max_length=7),
        ),
        migrations.AddField(
            model_name="sala",
            name="border",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="sala",
            name="border_color",
            field=models.CharField(default="#0000ff", max_length=7),
        ),
        migrations.AlterField(
            model_name="exposicion",
            name="sala",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exposiciones",
                to="Museo.sala",
            ),
        ),
    ]
