# Generated by Django 5.0.6 on 2024-10-09 18:48

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Museo", "0005_exposicion_bg_color_exposicion_border_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exposicion",
            name="bg_color",
            field=colorfield.fields.ColorField(
                default="#04ff00", image_field=None, max_length=25, samples=None
            ),
        ),
        migrations.AlterField(
            model_name="exposicion",
            name="border_color",
            field=colorfield.fields.ColorField(
                default="#0000ff", image_field=None, max_length=25, samples=None
            ),
        ),
        migrations.AlterField(
            model_name="museo",
            name="bg_color",
            field=colorfield.fields.ColorField(
                default="#04ff00", image_field=None, max_length=25, samples=None
            ),
        ),
        migrations.AlterField(
            model_name="museo",
            name="border_color",
            field=colorfield.fields.ColorField(
                default="#0000ff", image_field=None, max_length=25, samples=None
            ),
        ),
        migrations.AlterField(
            model_name="sala",
            name="bg_color",
            field=colorfield.fields.ColorField(
                default="#04ff00", image_field=None, max_length=25, samples=None
            ),
        ),
        migrations.AlterField(
            model_name="sala",
            name="border_color",
            field=colorfield.fields.ColorField(
                default="#0000ff", image_field=None, max_length=25, samples=None
            ),
        ),
    ]
